/**
 * Fetch Pretendard Variable as unicode-range subsets and generate the CSS.
 *
 * The single PretendardVariable.woff2 is 2.0MB because it carries the whole
 * Hangul syllable block, and next/font preloads it — which made it the site's
 * LCP bottleneck (2.6s with it, 1.4s without; docs/media/performance-check.md).
 *
 * Subsetting by hand to the glyphs the site uses today would be smaller still,
 * but every future post could introduce a syllable that was not in the subset
 * and render as tofu. The upstream dynamic subset avoids that entirely: full
 * coverage is still declared, split across ~90 ranges, and the browser fetches
 * only the ranges a page actually paints.
 *
 * Self-hosted rather than served from the CDN: the site runs a strict
 * nonce-based CSP, and a third-party origin would cost a fresh DNS + TLS
 * handshake on the critical path — the opposite of the point.
 *
 * Run: npm run fetch:fonts   (only needed when bumping PRETENDARD_VERSION)
 */
import fs from 'fs'
import path from 'path'

const PRETENDARD_VERSION = 'v1.3.9'
const BASE = `https://cdn.jsdelivr.net/gh/orioncactus/pretendard@${PRETENDARD_VERSION}/packages/pretendard/dist/web/variable`
const SUBSET_CSS = `${BASE}/pretendardvariable-dynamic-subset.css`

const OUT_DIR = path.join(process.cwd(), 'public', 'fonts', 'pretendard')
const CSS_OUT = path.join(process.cwd(), 'src', 'app', 'pretendard.css')
/** Where the browser will ask for them, matching public/ semantics. */
const PUBLIC_PREFIX = '/fonts/pretendard'

interface Face {
  file: string
  unicodeRange: string
}

/** Pull (file, unicode-range) out of each @font-face; everything else in the
 *  upstream CSS is re-stated locally so the output is ours, not a copy. */
function parseFaces(css: string): Face[] {
  const faces: Face[] = []
  for (const block of css.split('@font-face').slice(1)) {
    const file = /url\(\.?\/?([^)'"]*?([^/)'"]+\.woff2))\)/.exec(block)?.[2]
    const unicodeRange = /unicode-range:\s*([^;]+);/.exec(block)?.[1]?.trim()
    if (file && unicodeRange) faces.push({ file, unicodeRange })
  }
  return faces
}

async function download(url: string): Promise<Buffer> {
  const res = await fetch(url)
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`)
  return Buffer.from(await res.arrayBuffer())
}

function renderCss(faces: Face[]): string {
  const header = `/* Pretendard Variable ${PRETENDARD_VERSION}, split into unicode-range subsets.
 *
 * GENERATED by scripts/fetch-pretendard-subset.ts — do not edit by hand.
 *
 * A page only downloads the ranges it actually paints, so an English page pulls
 * a few tens of KB instead of the 2.0MB single file this replaces. Coverage is
 * unchanged, so no future Korean syllable can render as tofu.
 *
 * font-display: swap keeps text visible while a range is in flight; the metric
 * overrides that next/font used to supply are unnecessary here because the
 * fallback stack in globals.css is already Korean-capable.
 */\n\n`

  const blocks = faces.map(
    (f) => `@font-face {
  font-family: 'Pretendard Variable';
  font-style: normal;
  font-display: swap;
  font-weight: 45 920;
  src: url('${PUBLIC_PREFIX}/${f.file}') format('woff2-variations');
  unicode-range: ${f.unicodeRange};
}`,
  )

  return header + blocks.join('\n\n') + '\n'
}

async function main() {
  console.log(`fetching subset manifest — pretendard ${PRETENDARD_VERSION}`)
  const css = await download(SUBSET_CSS).then((b) => b.toString('utf8'))
  const faces = parseFaces(css)
  if (faces.length === 0) throw new Error('no @font-face blocks parsed — upstream layout changed')
  console.log(`${faces.length} subsets`)

  fs.mkdirSync(OUT_DIR, { recursive: true })

  let total = 0
  for (const [i, face] of faces.entries()) {
    const buf = await download(`${BASE}/woff2-dynamic-subset/${face.file}`)
    fs.writeFileSync(path.join(OUT_DIR, face.file), buf)
    total += buf.byteLength
    if ((i + 1) % 20 === 0 || i === faces.length - 1) {
      console.log(`  ${i + 1}/${faces.length}`)
    }
  }

  fs.writeFileSync(CSS_OUT, renderCss(faces), 'utf8')

  const kb = (n: number) => `${Math.round(n / 1024)}KB`
  const sizes = faces
    .map((f) => fs.statSync(path.join(OUT_DIR, f.file)).size)
    .sort((a, b) => b - a)
  console.log(`\nwrote ${faces.length} files, ${kb(total)} total`)
  console.log(`largest subset ${kb(sizes[0])}, median ${kb(sizes[Math.floor(sizes.length / 2)])}`)
  console.log(`css -> ${path.relative(process.cwd(), CSS_OUT)}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
